language: c
script:
  - ./bootstrap
  - ./configure --with-gmetad --with-perl=/usr --enable-status
  - make all
sudo: false
addons:
  apt:
    packages:
    - libapr1-dev
    - libaprutil1-dev
    - libconfuse-dev
    - libexpat1-dev
    - libpcre3-dev
    - libssl-dev
    - librrd-dev
    - libperl-dev
    - libtool
    - m4
    - gperf
    - zlib1g-dev
    - pkg-config
